from __future__ import annotations
from typing import TYPE_CHECKING
from dataclasses import dataclass

if TYPE_CHECKING:  # pragma: no cover
    from fifo_dev_dsl.dia.dsl.elements.slot import Slot
    from fifo_dev_dsl.dia.dsl.elements.base import DslBase
    from fifo_dev_common.introspection.mini_docstring import MiniDocStringType

@dataclass
class InteractionRequest:
    """
    Prompt generated by a DSL element asking the user for input.

    Interaction requests are created when resolution encounters a node that
    requires clarification from the user, such as an ASK or QUERY_USER element.
    The `message` is shown to the user, and their response is later captured in
    an InteractionAnswer.

    Example:
        If the user asks a robotic arm to "retrieve three screws" and the system
        needs more detail, it might ask: "What length do you need?" In this case:

            message = "What length do you need?"
            expected_type = MiniDocStringType(str)
            slot = Slot(name="length")
            requester = Ask(...)

    Attributes:
        message (str):
            The text shown to the user. It may be:
            - A question (e.g., "What length do you need?")
            - An instruction (e.g., "Place the screws on the tray.")
            - An answer, especially in QUERY_USER scenarios
              (e.g., "The inventory contains 3 screws.")

        expected_type (MiniDocStringType):
            A MiniDocStringType instance indicating the expected format of the
            user's reply. This can be used for validation or UI adaptation.

        requester (DslBase):
            The DSL node that generated this request. Used to route the answer
            to the correct point in the DSL resolution tree.

        slot (Slot or None):
            If the request is clarifying a specific slot (e.g., "length"),
            this is the slot being clarified. Otherwise, it is None. It can be
            used by the UI to provide additional context to the user.
    """

    message: str
    expected_type: MiniDocStringType
    requester: DslBase
    slot: Slot | None = None


@dataclass
class InteractionAnswer:
    """
    User-provided response to an InteractionRequest.

    This holds the raw reply given by the user in response to a request
    generated during resolution. While the content is always stored as a string,
    its format is expected to match the type declared in the corresponding
    MiniDocStringType from the original request.

    Attributes:
        content (str):
            The raw answer text supplied by the user. Although stored as a string,
            it should match the expected format (e.g., "42" for int) based on the
            MiniDocStringType declared in the InteractionRequest.

        consumed (bool):
            Whether the answer has already been used during resolution.
            Once consumed, an answer is not reused — this ensures each response
            is only applied once, even across retries or clarification loops.
    """

    content: str
    consumed: bool = False


@dataclass
class Interaction:
    """
    User-submitted response that pairs a prior InteractionRequest with an answer.

    An Interaction is constructed by combining a previously issued request with
    the user's response. It is passed back into the resolution loop to integrate
    the user's answer and continue processing.

    This pattern allows the framework to maintain a clean separation between
    the prompt (request) and its answer, while ensuring the full context is
    preserved.

    Attributes:
        request (InteractionRequest):
            The original request shown to the user.

        answer (InteractionAnswer):
            The user-provided response to the request.
    """

    request: InteractionRequest
    answer: InteractionAnswer
