name: Tests

on:
  push:
  workflow_dispatch:  # Allows manual runs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout fifo-tool-airlock-model-env
        uses: actions/checkout@v4
        with:
          repository: gh9869827/fifo-tool-airlock-model-env
          path: external/fifo-tool-airlock-model-env

      - name: Checkout fifo-dev-common
        uses: actions/checkout@v4
        with:
          repository: gh9869827/fifo-dev-common
          path: external/fifo-dev-common

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e external/fifo-tool-airlock-model-env
          python -m pip install -e external/fifo-dev-common
          python -m pip install -e .
          python -m pip install pytest

      - name: Run tests
        run: pytest
