name: Tests

on:
  push:
  workflow_dispatch:  # Allows manual runs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout fifo_tool_airlock_model_env
        uses: actions/checkout@v4
        with:
          repository: gh9869827/fifo_tool_airlock_model_env
          path: ../fifo_tool_airlock_model_env

      - name: Checkout fifo_dev_common
        uses: actions/checkout@v4
        with:
          repository: gh9869827/fifo_dev_common
          path: ../fifo_dev_common

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ../fifo_tool_airlock_model_env
          python -m pip install -e ../fifo_dev_common
          python -m pip install -e .
          python -m pip install pytest

      - name: Run tests
        run: pytest
